spring:
  application:
    name: bingo-map

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080