-- ddl-auto: none, so tables must be created manually.
-- Sequence-based PK (IDENTITY/OFFSET-FETCH not supported by this Oracle instance).

CREATE TABLE TB_COMMUNITY_POST (
    POST_ID      NUMBER PRIMARY KEY,
    USER_ID      NUMBER NOT NULL,
    TITLE        VARCHAR2(200) NOT NULL,
    CONTENT      CLOB NOT NULL,
    TAGS         VARCHAR2(200),
    VIEW_COUNT   NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP
    -- , CONSTRAINT FK_COMMUNITY_POST_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
);

CREATE SEQUENCE SEQ_COMMUNITY_POST START WITH 1 INCREMENT BY 1 NOCACHE;