-- ddl-auto: none, so tables must be created manually.
-- Sequence-based PK (this Oracle instance doesn't support IDENTITY/OFFSET-FETCH syntax).
-- TB_USER, TB_RESTAURANT must exist first if you want to enable the FK constraints below.

CREATE TABLE TB_REVIEW (
    REVIEW_ID        NUMBER PRIMARY KEY,
    USER_ID          NUMBER NOT NULL,
    RESTAURANT_ID    NUMBER NOT NULL,
    RATING           NUMBER(2,1) NOT NULL,
    CONTENT          CLOB NOT NULL,
    VISIT_DATE       DATE,
    VISIT_TIME_SLOT  VARCHAR2(20),
    VISIT_PURPOSE    VARCHAR2(20),
    RECOMMEND_YN     NUMBER(1),
    HELP_COUNT       NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    -- , CONSTRAINT FK_REVIEW_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
    -- , CONSTRAINT FK_REVIEW_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES TB_RESTAURANT(RESTAURANT_ID)
);

CREATE SEQUENCE SEQ_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE TB_REVIEW_IMAGE (
    REVIEW_IMAGE_ID  NUMBER PRIMARY KEY,
    REVIEW_ID        NUMBER NOT NULL,
    IMAGE_URL        VARCHAR2(255) NOT NULL,
    SORT_ORDER       NUMBER,
    CONSTRAINT FK_REVIEW_IMAGE_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES TB_REVIEW(REVIEW_ID)
);

CREATE SEQUENCE SEQ_REVIEW_IMAGE START WITH 1 INCREMENT BY 1 NOCACHE;

select * FROM TB_REVIEW;
DELETE FROM TB_REVIEW_IMAGE;
DELETE FROM TB_REVIEW;
COMMIT;

