-- ============================================================
-- BinGo Map 다국어 콘텐츠 번역 테이블 추가
--
-- 실행 순서:
--   1. DB/BinGoMap_팀_공동쿼리_최종_12테이블_ISPUBLISHED_Y.sql 실행
--   2. 이 파일을 한 번 실행
--
-- 기존 테이블이나 데이터를 삭제/수정하지 않는 추가 스키마입니다.
-- 번역 테이블은 처음에는 비어 있습니다. 아래 언어 목록만 등록합니다.
-- 번역 상태가 REVIEWED인 데이터만 화면에 노출하고, 그 외에는 원문을 사용하도록
-- 애플리케이션에서 처리합니다.
-- ============================================================

-- 1. 지원 언어 목록
CREATE TABLE SUPPORTED_LANGUAGES (
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    DISPLAY_NAME        VARCHAR2(40)    NOT NULL,
    IS_ENABLED          CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SUPPORTED_LANGUAGES PRIMARY KEY (LOCALE_CODE),
    CONSTRAINT CK_SUPPORTED_LANG_ENABLED CHECK (IS_ENABLED IN ('Y', 'N'))
);

INSERT INTO SUPPORTED_LANGUAGES (LOCALE_CODE, DISPLAY_NAME, IS_ENABLED)
VALUES ('ko', '한국어', 'Y');

INSERT INTO SUPPORTED_LANGUAGES (LOCALE_CODE, DISPLAY_NAME, IS_ENABLED)
VALUES ('en', 'English', 'Y');

INSERT INTO SUPPORTED_LANGUAGES (LOCALE_CODE, DISPLAY_NAME, IS_ENABLED)
VALUES ('ja', '日本語', 'Y');

-- 2. 식당 번역
CREATE TABLE RESTAURANT_TRANSLATIONS (
    RESTAURANT_ID       NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    NAME                VARCHAR2(500)   NOT NULL,
    CATEGORY            VARCHAR2(500),
    TAGS                VARCHAR2(1000),
    DESCRIPTION         CLOB,
    ADDRESS             VARCHAR2(4000),
    OPENING_HOURS       VARCHAR2(2000),
    SEAT_INFO           VARCHAR2(300),
    RESERVATION_INFO    VARCHAR2(300),
    PAYMENT_METHODS     VARCHAR2(600),
    LANGUAGES_LABEL     VARCHAR2(600),
    MENU_NAME           VARCHAR2(500),
    MENU_DESCRIPTION    CLOB,
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RESTAURANT_TRANS PRIMARY KEY (RESTAURANT_ID, LOCALE_CODE),
    CONSTRAINT FK_REST_TRANS_RESTAURANT FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANTS (RESTAURANT_ID),
    CONSTRAINT FK_REST_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_REST_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_REST_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 3. 별도 식당 메뉴 번역
CREATE TABLE RESTAURANT_MENU_TRANSLATIONS (
    MENU_ID             NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    NAME                VARCHAR2(500)   NOT NULL,
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MENU_TRANSLATIONS PRIMARY KEY (MENU_ID, LOCALE_CODE),
    CONSTRAINT FK_MENU_TRANS_MENU FOREIGN KEY (MENU_ID)
        REFERENCES RESTAURANT_MENU (ID),
    CONSTRAINT FK_MENU_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_MENU_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_MENU_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 4. 쓰레기통 안내 번역
CREATE TABLE WASTE_BIN_TRANSLATIONS (
    WASTE_BIN_ID        NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    NAME                VARCHAR2(300),
    CATEGORY_LABEL      VARCHAR2(100),
    ADDRESS             VARCHAR2(1000),
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WASTE_BIN_TRANS PRIMARY KEY (WASTE_BIN_ID, LOCALE_CODE),
    CONSTRAINT FK_BIN_TRANS_BIN FOREIGN KEY (WASTE_BIN_ID)
        REFERENCES WASTE_BIN (ID),
    CONSTRAINT FK_BIN_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_BIN_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_BIN_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 5. 공지 번역
CREATE TABLE NOTICE_TRANSLATIONS (
    NOTICE_ID           NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    TITLE               VARCHAR2(600)   NOT NULL,
    CONTENT             CLOB            NOT NULL,
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NOTICE_TRANSLATIONS PRIMARY KEY (NOTICE_ID, LOCALE_CODE),
    CONSTRAINT FK_NOTICE_TRANS_NOTICE FOREIGN KEY (NOTICE_ID)
        REFERENCES NOTICES (ID),
    CONSTRAINT FK_NOTICE_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_NOTICE_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_NOTICE_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 6. 리뷰 번역 (원문 REVIEWS.CONTENT는 유지)
CREATE TABLE REVIEW_TRANSLATIONS (
    REVIEW_ID           NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    CONTENT             CLOB            NOT NULL,
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REVIEW_TRANSLATIONS PRIMARY KEY (REVIEW_ID, LOCALE_CODE),
    CONSTRAINT FK_REVIEW_TRANS_REVIEW FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEWS (ID),
    CONSTRAINT FK_REVIEW_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_REVIEW_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_REVIEW_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 7. 커뮤니티 게시글 번역 (원문 COMMUNITY_POST는 유지)
CREATE TABLE COMMUNITY_POST_TRANSLATIONS (
    POST_ID             NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    TITLE               VARCHAR2(600)   NOT NULL,
    CONTENT             CLOB            NOT NULL,
    TAGS                VARCHAR2(600),
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_COMMUNITY_POST_TRANS PRIMARY KEY (POST_ID, LOCALE_CODE),
    CONSTRAINT FK_POST_TRANS_POST FOREIGN KEY (POST_ID)
        REFERENCES COMMUNITY_POST (ID),
    CONSTRAINT FK_POST_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_POST_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_POST_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 8. 커뮤니티 댓글 번역 (원문 COMMUNITY_COMMENT는 유지)
CREATE TABLE COMMUNITY_COMMENT_TRANSLATIONS (
    COMMENT_ID          NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    CONTENT             CLOB            NOT NULL,
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_COMMUNITY_COMMENT_TR PRIMARY KEY (COMMENT_ID, LOCALE_CODE),
    CONSTRAINT FK_COMMENT_TRANS_COMMENT FOREIGN KEY (COMMENT_ID)
        REFERENCES COMMUNITY_COMMENT (ID),
    CONSTRAINT FK_COMMENT_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_COMMENT_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_COMMENT_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 9. 쓰레기통 제보 번역 (원문 BIN_REPORTS는 유지)
CREATE TABLE BIN_REPORT_TRANSLATIONS (
    REPORT_ID           NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    NAME                VARCHAR2(400),
    CATEGORY_LABEL      VARCHAR2(100),
    ADDRESS             VARCHAR2(1000),
    DESCRIPTION         CLOB,
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BIN_REPORT_TRANS PRIMARY KEY (REPORT_ID, LOCALE_CODE),
    CONSTRAINT FK_REPORT_TRANS_REPORT FOREIGN KEY (REPORT_ID)
        REFERENCES BIN_REPORTS (ID),
    CONSTRAINT FK_REPORT_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_REPORT_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_REPORT_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

-- 10. 시스템 점검 안내 번역
CREATE TABLE SYSTEM_SETTINGS_TRANSLATIONS (
    SETTING_ID          NUMBER(19)      NOT NULL,
    LOCALE_CODE         VARCHAR2(10)    NOT NULL,
    SOURCE_LOCALE_CODE  VARCHAR2(10),
    MAINTENANCE_MESSAGE VARCHAR2(1000)  NOT NULL,
    TRANSLATION_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SYSTEM_SETTINGS_TR PRIMARY KEY (SETTING_ID, LOCALE_CODE),
    CONSTRAINT FK_SETTINGS_TRANS_SETTING FOREIGN KEY (SETTING_ID)
        REFERENCES SYSTEM_SETTINGS (ID),
    CONSTRAINT FK_SETTINGS_TRANS_LOCALE FOREIGN KEY (LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT FK_SETTINGS_TRANS_SOURCE FOREIGN KEY (SOURCE_LOCALE_CODE)
        REFERENCES SUPPORTED_LANGUAGES (LOCALE_CODE),
    CONSTRAINT CK_SETTINGS_TRANS_STATUS
        CHECK (TRANSLATION_STATUS IN ('PENDING', 'MACHINE_DRAFT', 'REVIEWED'))
);

COMMIT;

-- 실행 확인
SELECT LOCALE_CODE, DISPLAY_NAME, IS_ENABLED
FROM SUPPORTED_LANGUAGES
ORDER BY LOCALE_CODE;

SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'SUPPORTED_LANGUAGES',
    'RESTAURANT_TRANSLATIONS',
    'RESTAURANT_MENU_TRANSLATIONS',
    'WASTE_BIN_TRANSLATIONS',
    'NOTICE_TRANSLATIONS',
    'REVIEW_TRANSLATIONS',
    'COMMUNITY_POST_TRANSLATIONS',
    'COMMUNITY_COMMENT_TRANSLATIONS',
    'BIN_REPORT_TRANSLATIONS',
    'SYSTEM_SETTINGS_TRANSLATIONS'
)
ORDER BY TABLE_NAME;
