-- ============================================================
-- [10/01 유해성] 커뮤니티 좋아요 테이블만 추가 (기존 데이터 유지)
-- 이미 팀 공통쿼리(최종)로 DB를 만든 경우, 이 파일만 F5로 실행하세요.
-- SETUP 을 다시 돌릴 필요 없음. 앱은 실행 중이어도 되지만, 끝나면 재시작하세요.
-- 두 번 실행하면 "이미 존재" 오류가 나는데, 그건 이미 추가된 상태라는 뜻이에요.
-- ============================================================

CREATE SEQUENCE SEQ_COMMUNITY_POST_LIKE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE COMMUNITY_POST_LIKE (
    ID          NUMBER(19)      NOT NULL,
    POST_ID     NUMBER(19)      NOT NULL,
    USER_ID     NUMBER(19)      NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_COMMUNITY_POST_LIKE PRIMARY KEY (ID),
    CONSTRAINT UK_COMMUNITY_POST_LIKE UNIQUE (POST_ID, USER_ID),
    CONSTRAINT FK_COMMUNITY_POST_LIKE_POST
        FOREIGN KEY (POST_ID) REFERENCES COMMUNITY_POST(ID),
    CONSTRAINT FK_COMMUNITY_POST_LIKE_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE OR REPLACE TRIGGER COMMUNITY_POST_LIKE_BI
BEFORE INSERT ON COMMUNITY_POST_LIKE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_COMMUNITY_POST_LIKE.NEXTVAL
        INTO :NEW.ID
        FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

COMMIT;

-- 확인: COMMUNITY_POST_LIKE 0 / COMMUNITY_POST_LIKE_BI ENABLED 가 나오면 성공
SELECT 'COMMUNITY_POST_LIKE' AS TABLE_NAME, COUNT(*) AS CNT FROM COMMUNITY_POST_LIKE;

SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'COMMUNITY_POST_LIKE_BI';
